<?xml version="1.0" encoding="UTF-8"?>
<CONFIG>
  <Makefile Value="2"/>
  <Params Value=" -Fu../source;../source.vcl;C:/lazarus/packager/units/$(CPU_TARGET)-$(OS_TARGET);C:/lazarus/components/lazutils/lib/$(CPU_TARGET)-$(OS_TARGET);C:/lazarus/lcl/units/$(CPU_TARGET)-$(OS_TARGET);C:/lazarus/lcl/units/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);.  -MDelphi -Scghi -CX -O4 -g -gl -gh -Xg -l -vewnhibq -dLCL -dLCL$(LCL_PLATFORM) PasLibVlcPlayer.pas"/>
</CONFIG>
